[build-system]
requires = [
    "setuptools",
    "wheel",
    "pyobjc-framework-Quartz==7.3",
    "mouse==0.7.1; sys_platform == 'win32'",
    "mouse==0.7.1; sys_platform == 'linux'",
    "macmouse==0.7.4; sys_platform == 'darwin'"
]
build-backend = "setuptools.build_meta"